export const productos = [
  {
    id: 1,
    title: "Facturas",
    price: 1100,
    stock: 4,
    description:
      "Gran variedad de facturas de crema pastelera, dulce de membrillo y dulce de leche con y sin decoraciones",
    category: "dulce",
    img: "../public/facturastodas.jpg",
  },
  {
    id: 2,
    title: "Tortas",
    price: 1500,
    stock: 10,
    description: "Variedad de tortas disponibles y se realizan por encargue.",
    category: "dulce",
    img: "../public/tortas.jpg",
  },
  {
    id: 3,
    title: " Alfajores",
    price: 1500,
    stock: 25,
    description: "Alfajores de dulce de leche tipo marplatenses y de maicena",
    category: "dulce",
    img: "../public/alfajorescuadrado.jpg",
  },
  {
    id: 4,
    title: "Cupckaes",
    price: 2500,
    stock: 8,
    description: "Con y sin baño de chocoloate negro",
    category: "dulce",
    img: "../public/cupckaes_choc.jpg",
  },
  {
    id: 5,
    title: "Pepitas",
    price: 2200,
    stock: 14,
    description: "Con dulce de membrillo de la mejor calidad",
    category: "dulce",
    img: "../public/pepitas.jpg",
  },
  {
    id: 6,
    title: "Cañoncitos",
    price: 3500,
    stock: 6,
    description: "Con relleno de dulce de leche",
    category: "dulce",
    img: "../public/cañoncitos.jpg",
  },
  {
    id: 7,
    title: "Galletas",
    price: 1500,
    stock: 19,
    description:
      "Gran variedad de galletas, entre ellas, galletas con chips de chocolate",
    category: "dulce",
    img: "../public/galel_chips_choc.jpg",
  },
  {
    id: 8,
    title: "Bizcochos",
    price: 1500,
    stock: 15,
    description: "Los clásicos redonditos o cuadraditos hojaldrados",
    category: "dulce",
    img: "../public/bizcosalados.jpg",
  },
  {
    id: 9,
    title: "Chipaquitos",
    price: 1600,
    stock: 12,
    description: "No apto para vegetarianos",
    category: "salado",
    img: "../public/chipaquitos.jpg",
  },
  {
    id: 10,
    title: "Pan francés",
    price: 500,
    stock: 25,
    description: "Pan francés tipo mignon",
    category: "salado",
    img: "../public/panfrancés.jpg",
  },
  {
    id: 11,
    title: "Rosca de Pascua",
    price: 800,
    stock: 14,
    description: "Disponible solo durante Pascuas",
    category: "especialidad",
    img: "../public/rosca-pascua.jpg",
  },
  {
    id: 12,
    title: "Pan Dulce",
    price: 2000,
    stock: 26,
    description: "Disponible solo durante el mes de diciembre",
    category: "especialidad",
    img: "../public/pandulce.jpg",
  },
  {
    id: 13,
    title: "Pan de miga",
    price: 3500,
    stock: 23,
    description: "Disponible solo durante el mes de diciembre",
    category: "especialidad",
    img: "../public/panmiga.jpg",
  },
];