export const productos = [
  {
    id: 1,
    title: "Facturas",
    price: 1100,
    stock: 4,
    description:
      "Gran variedad de facturas de crema pastelera, dulce de membrillo y dulce de leche con y sin decoraciones",
    category: "dulce",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142069/Panader%C3%ADa%20S%C3%A1nchez/facturastodas_povmah.jpg",
  },
  {
    id: 2,
    title: "Tortas",
    price: 1500,
    stock: 15,
    description: "Variedad de tortas disponibles y se realizan por encargue.",
    category: "dulce",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142072/Panader%C3%ADa%20S%C3%A1nchez/tortas_rqv2aj.jpg",
  },
  {
    id: 3,
    title: " Alfajores",
    price: 1500,
    stock: 25,
    description: "Alfajores de dulce de leche tipo marplatenses y de maicena",
    category: "dulce",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142068/Panader%C3%ADa%20S%C3%A1nchez/alfajorescuadrado_zbc1bj.jpg",
  },
  {
    id: 4,
    title: "Cupcakes",
    price: 2500,
    stock: 8,
    description: "Con y sin baño de chocoloate negro",
    category: "dulce",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142068/Panader%C3%ADa%20S%C3%A1nchez/cupcakes_choc_aaioeb.jpg",
  },
  {
    id: 5,
    title: "Pepitas",
    price: 2200,
    stock: 14,
    description: "Con dulce de membrillo de la mejor calidad",
    category: "dulce",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142071/Panader%C3%ADa%20S%C3%A1nchez/pepitas_lfs6wt.jpg",
  },
  {
    id: 6,
    title: "Cañoncitos",
    price: 3500,
    stock: 6,
    description: "Con relleno de dulce de leche",
    category: "dulce",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142068/Panader%C3%ADa%20S%C3%A1nchez/ca%C3%B1oncitos_aiqs19.jpg",
  },
  {
    id: 7,
    title: "Galletas",
    price: 1500,
    stock: 19,
    description:
      "Gran variedad de galletas, entre ellas, galletas con chips de chocolate",
    category: "dulce",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142070/Panader%C3%ADa%20S%C3%A1nchez/galle_chips_choc_einnte.jpg",
  },
  {
    id: 8,
    title: "Bizcochos",
    price: 1500,
    stock: 15,
    description: "Los clásicos redonditos o cuadraditos hojaldrados",
    category: "dulce",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142068/Panader%C3%ADa%20S%C3%A1nchez/bizcosalados_y2fkoc.jpg",
  },
  {
    id: 9,
    title: "Chipaquitos",
    price: 1600,
    stock: 12,
    description: "No apto para vegetarianos",
    category: "salado",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142069/Panader%C3%ADa%20S%C3%A1nchez/chipaquitos_t3j6kc.jpg",
  },
  {
    id: 10,
    title: "Pan francés",
    price: 500,
    stock: 25,
    description: "Pan francés tipo mignon",
    category: "salado",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142071/Panader%C3%ADa%20S%C3%A1nchez/panfranc%C3%A9s_lqecx1.jpg",
  },
  {
    id: 11,
    title: "Rosca de Pascua",
    price: 800,
    stock: 14,
    description: "Disponible solo durante Pascuas",
    category: "especialidad",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142072/Panader%C3%ADa%20S%C3%A1nchez/rosca-pascua_oldshe.jpg",
  },
  {
    id: 12,
    title: "Pan Dulce",
    price: 2000,
    stock: 26,
    description: "Disponible solo durante el mes de diciembre",
    category: "especialidad",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142072/Panader%C3%ADa%20S%C3%A1nchez/pandulce_gkdrjv.jpg",
  },
  {
    id: 13,
    title: "Pan de miga",
    price: 3500,
    stock: 23,
    description: "Disponible solo durante el mes de diciembre",
    category: "especialidad",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142072/Panader%C3%ADa%20S%C3%A1nchez/panmiga_dyjsn9.jpg",
  },
  {
    title: "Lengüitas",
    price: 2500,
    stock: 4,
    description: "Con dulce de leche de la mejor calidad",
    category: "dulce",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142071/Panader%C3%ADa%20S%C3%A1nchez/leng%C3%BCitas_qk9f0u.jpg",
    id: 14,
  },
  {
    title: "Palitos",
    price: 1500,
    stock: 5,
    description: "Bañados en chocolate de leche",
    category: "dulce",
    img: "https://res.cloudinary.com/dp8auiwtw/image/upload/v1686142071/Panader%C3%ADa%20S%C3%A1nchez/palitoschocolate_gepktt.jpg",
    id: 15,
  },
];